# Generated by Django 5.1 on 2024-08-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctordetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_img', models.ImageField(upload_to='doctor/')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_spec', models.CharField(max_length=50)),
            ],
        ),
    ]
