# Generated by Django 5.1 on 2024-09-26 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointmentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetail',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctordetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
