# Generated by Django 5.1 on 2024-09-28 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_appointmentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetail',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctordetail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentdetail',
            name='number',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='age',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='email',
            field=models.IntegerField(max_length=100),
        ),
    ]
