# Generated by Django 5.1 on 2024-09-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointmentdetail_doctor_alter_appointmentdetail_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetail',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
