# Generated by Django 5.1 on 2024-09-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointmentdetail_doctor_appointmentdetail_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentdetail',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='reason',
            field=models.CharField(max_length=255),
        ),
    ]
