# Generated by Django 5.1 on 2024-09-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_appointmentdetail_doctor_doctordetail_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctordetail',
            name='user',
        ),
    ]
