# Generated by Django 5.1 on 2024-09-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_doctordetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.userdata'),
            preserve_default=False,
        ),
    ]
