# Generated by Django 5.1 on 2024-09-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_appointmentdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetail',
            name='doc_img',
            field=models.ImageField(default=1, upload_to='doctor/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentdetail',
            name='doc_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointmentdetail',
            name='doc_spec',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
