# Generated by Django 5.1 on 2024-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_userdata_options_alter_userdata_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
        migrations.AlterModelManagers(
            name='userdata',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointmentdetail',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
