# Generated by Django 5.1 on 2024-09-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_userdata_password'),
    ]

    operations = [
    ]
